name: Deploy CDK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install AWS CDK globally
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: |
          npm install @aws-cdk/core @aws-cdk/aws-glue @aws-cdk/aws-iam @aws-cdk/aws-s3 ts-node typescript

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check current directory
        run: pwd

      - name: List files in current directory
        run: ls -la

      - name: Check contents of Glue.ts
        run: cat Glue.ts

      - name: Create cdk.out directory if it does not exist
        run: mkdir -p cdk.out

      - name: List files in cdk.out directory
        run: ls -la cdk.out

      - name: Check Node.js version
        run: node -v

      - name: Check npm version
        run: npm -v

      - name: Check TypeScript version
        run: npx tsc -v

      - name: Synthesize CDK stack
        run: cdk synth --app "npx ts-node Glue.ts"
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy CDK stack
        run: cdk deploy --app "npx ts-node Glue.ts" --require-approval never
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
